services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - ENV=${ENV:-development}
      - APP_NAME=${APP_NAME:-Voc on Steroid}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - DATABASE_URL=postgres://user:password@postgres:5432/voconsteroid
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-dev_secret_key}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./back:/app
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voconsteroid
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d voconsteroid"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_/data

volumes:
  postgres_
  redis_
