// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/words/autocomplete": {
            "get": {
                "description": "Get word suggestions based on prefix",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get autocomplete suggestions",
                "parameters": [
                    {
                        "minLength": 2,
                        "type": "string",
                        "description": "The prefix to search for",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "fr",
                            "en"
                        ],
                        "type": "string",
                        "description": "Language code",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.AutoCompleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/words/recent": {
            "get": {
                "description": "Get recently searched words",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get recent words",
                "parameters": [
                    {
                        "enum": [
                            "fr",
                            "en"
                        ],
                        "type": "string",
                        "default": "fr",
                        "description": "Language code",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Maximum number of words to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.RecentWordsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/words/search": {
            "post": {
                "description": "Search for a word by text and language",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Search for a word",
                "parameters": [
                    {
                        "description": "Word search request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.WordSearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.WordSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/words/{wordId}/related": {
            "get": {
                "description": "Get synonyms and antonyms for a word",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get related words",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Word ID",
                        "name": "wordId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.RelatedWordsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.AutoCompleteResponse": {
            "type": "object",
            "properties": {
                "suggestions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "server.RecentWordsResponse": {
            "type": "object",
            "properties": {
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word.Word"
                    }
                }
            }
        },
        "server.RelatedWordsResponse": {
            "type": "object",
            "properties": {
                "antonyms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word.Word"
                    }
                },
                "source_word": {
                    "$ref": "#/definitions/word.Word"
                },
                "synonyms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word.Word"
                    }
                }
            }
        },
        "server.WordSearchRequest": {
            "type": "object",
            "required": [
                "language",
                "text"
            ],
            "properties": {
                "language": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "server.WordSearchResponse": {
            "type": "object",
            "properties": {
                "word": {
                    "$ref": "#/definitions/word.Word"
                }
            }
        },
        "word.Definition": {
            "type": "object",
            "properties": {
                "examples": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "gender": {
                    "type": "string"
                },
                "language_specifics": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pronunciation": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "word_type": {
                    "description": "noun, verb, adjective, etc.",
                    "type": "string"
                }
            }
        },
        "word.Word": {
            "type": "object",
            "properties": {
                "antonyms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "definitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/word.Definition"
                    }
                },
                "etymology": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "lemma": {
                    "description": "Base form of the word",
                    "type": "string"
                },
                "search_terms": {
                    "description": "All searchable forms of the word",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "synonyms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "text": {
                    "description": "The canonical form",
                    "type": "string"
                },
                "translations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "usage_notes": {
                    "description": "General usage information",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
